from typing import Tuple

def create_keypair() -> Tuple[SigningKey, VerifyingKey]: ...

class SigningKey:
    def __init__(self, seed: bytes) -> None: ...
    def sign(self, msg: bytes) -> bytes: ...
    def get_verifying_key(self) -> VerifyingKey: ...
    def to_bytes(self) -> bytes: ...

class VerifyingKey:
    def to_bytes(self) -> bytes: ...

